### ISSUE TITLE
Sample Project-'JSONNSDataExtension.swift' File error 'Use of undeclared type 'Data''

### ISSUE THREAD

**Issue by DarwinZhao** [DanilaVladi/Microsoft-Cognitive-Services-Swift-SDK#4]
Just download from github,open `CognitiveServices.xcodeproj` file with Xcode 7.3.1 ,`JSONNSDataExtension.swift`  File error 'Use of undeclared type 'Data'':`extension Data {`

**Comment by DarwinZhao** [comment]
It seems because the version of Swift i used(2.2) ,it work in Swift3...

**Comment by DanilaVladi** [comment]
Yes, it's written for Swift 3.0

**Comment by DanilaVladi** [comment]
Everything prior this commit should run fine in previous versions of Swift and Xcode:

https://github.com/DanilaVladi/Microsoft-Cognitive-Services-Swift-SDK/tree/84a7723ead047d7bf246309193dfd20436fe05a1

**Comment by DarwinZhao** [comment]
Thanks
