### ISSUE TITLE
How to run the samples

### ISSUE THREAD

**Issue by tmsd32** [DanilaVladi/Microsoft-Cognitive-Services-Swift-SDK#5]
Hi,

After cloning the repo, I am simply attempting to run the samples to begin with. Please could you provide some advice as to how to do this from scratch? I receive an error stating, 

Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

whenever I try. 

Thanks in advance.

**Comment by DanilaVladi** [comment]
Hey @tommydudehead ,

I've updated the Swift Syntax to the current version... Can you try again? It should work now 👍 

Cheers,
Vladimir
