### ISSUE TITLE
Support for Objective C

### ISSUE THREAD

**Issue by thechaudharysab** [DanilaVladi/Microsoft-Cognitive-Services-Swift-SDK#6]
I want to use Computer Vision OCR Cognitive Service for iOS project written in Objective-C. Can you help? Or suggest some other SDK if you know.

Thanks

**Comment by DanilaVladi** [comment]
You can import a Swift bridging header inside your Objective-C.

#import "ProductModuleName-Swift.h"

(Replace ProductModuleName with yours)

Here is the Apple documentation:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Let me know if it worked :)
