### ISSUE TITLE
Thank for you the amazing Swift 3 Sample! Emotions got some issues though

### ISSUE THREAD

**Issue by babyghost-ys** [DanilaVladi/Microsoft-Cognitive-Services-Swift-SDK#7]
![screen shot 2016-11-28 at 12 11 27 am](https://cloud.githubusercontent.com/assets/5141074/20653113/7795f286-b4ff-11e6-8861-6a0b517ab97b.png)

First, thank you so much for such an amazing example. It helps me a lot to learn Swift 3 and Microsoft APIs. However, I found that if the image contains a person, it will crash like pictured above. I guess there is something wrong with the Emotions API? I have already put my correct key in the CognitiveServices.swift already. It looks like something has caused the optional value error. Do you mind to give me some clue on how to fix that? Thanks.

**Comment by DanilaVladi** [comment]
@babyghost666 I'll check this out and get back to you once it's fixed :)

**Comment by DanilaVladi** [comment]
@babyghost666 It should be fixed now.
